# 需要配置 Repository secrets
# ANDROID_JKS_GPG : 密钥的密文
# ANDROID_JKS_GPG_PASSWORD : 密文的密码
# ANDROID_JKS_KEY_PASSWORD : 密钥的 keyPassword
# ANDROID_JKS_STORE_PASSWORD : 密钥的 storePassword

name: Action

on:
  push:
    #    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-linux_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          # cache: 'gradle'

      - name: check-java
        run: java --version

      - id: ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r20b
          add-to-path: true

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.3'

      - name: check-flutter
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter --version

      - uses: actions/checkout@v3

      - name: prepare-resource
        run: |
          mkdir gts
          cd gts
          wget https://github.com/alx696/good-transport-server/releases/download/v1.0/gts-android_arm64
          wget https://github.com/alx696/good-transport-server/releases/download/v1.0/gts-amd64
          ls
          cd ..
          cd service
          wget https://github.com/alx696/good-transport-server/releases/download/v1.0/template.tar.gz
          tar zxf template.tar.gz
          rm template.tar.gz
          ls
          cd ..
          echo "恢复密钥"
          echo "${{ secrets.ANDROID_JKS_GPG }}" | tee android/app/lilu.red.jks.asc
          gpg -d --passphrase "${{ secrets.ANDROID_JKS_GPG_PASSWORD }}" --batch android/app/lilu.red.jks.asc > android/app/lilu.red.jks
          sha256sum android/app/lilu.red.jks

      - name: build
        env:
          ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
          ANDROID_JKS_KEY_PASSWORD: ${{ secrets.ANDROID_JKS_KEY_PASSWORD }}
          ANDROID_JKS_STORE_PASSWORD: ${{ secrets.ANDROID_JKS_STORE_PASSWORD }}
        run: |
          echo "构建Linux"
          mv gts/gts-amd64 service/
          flutter build linux --debug
          ls build/linux/x64/debug/bundle
          mv build/linux/x64/debug/bundle good-transport
          tar zcf good-transport-ubuntu.tar.gz good-transport
          rm -rf good-transport
          rm service/gts-amd64
          mkdir _public
          mv good-transport-ubuntu.tar.gz _public
          echo "构建Android"
          mv gts/gts-android_arm64 service/
          flutter build apk --debug
          ls build/app/outputs/flutter-apk
          mv build/app/outputs/flutter-apk/app-debug.apk _public/good-transport.apk
          echo "列出即将发布内容"
          ls _public

      - name: publish
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: _public/*
          overwrite: true
          body: "里路好传应用, 目前支持Ubuntu, Windows, Android. 访问 https://lilu.red 探索更多有趣的技术."

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            C:\hostedtoolcache\windows\flutter
            C:\Users\runneradmin\.pub-cache
          key: ${{ runner.os }}-cache

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.3'

      - name: check-flutter
        run: flutter --version

      - uses: actions/checkout@v3

      - name: download-server
        id: download-file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://github.com/alx696/good-transport-server/releases/download/v1.0/gts-amd64.exe'
          location: './service'

      - name: download-server-template
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://github.com/alx696/good-transport-server/releases/download/v1.0/template.tar.gz'
          location: './service'

      - name: prepare-resource
        run: |
          cd service
          tar zxf template.tar.gz
          ls
          cd ..

      - name: build
        run: |
          echo "构建Windows"
          flutter build windows --debug
          ls build/windows/runner/Debug
          mkdir _public
          mv build/windows/runner/Debug _public/good-transport
          ls _public

      - name: zip
        uses: thedoctor0/zip-release@main
        with:
          directory: '_public'
          type: 'zip'
          filename: 'good-transport-windows.zip'

      - name: publish
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: _public/good-transport-windows.zip
          overwrite: true
          body: "里路好传应用, 目前支持Ubuntu, Windows, Android. 访问 https://lilu.red 探索更多有趣的技术."
